-- Test batch generated from refactors/lsp_PwkGetVerifiedRxsWithManualPriority/Original.sql
-- Generated by tools/build_test_batch.py
-- DO NOT EDIT BY HAND; re-run the generator instead.

SET NOCOUNT OFF;  -- harness needs row counts visible

-- Parameter declarations
DECLARE @PatCustIdMask VarChar(20) = NULL;  -- TODO: supply test value
DECLARE @MultiToteRequired bit = 1;

-- Procedure body (verbatim from DDL, with EXEC lsp_DbLogSqlEvent commented out)
-- Drop Temp table if it exists
	If Object_Id('TempDb..#ReadyForPaperworkManPriority') Is Not Null
		Drop Table #ReadyForPaperworkManPriority

	-- Get ALL items ready for paperwork
	Select O.OrderId, O.GroupNum, O.Ndc, O.RxNum, O.OrderStatus, O.DateFilled, O.FillType, Po.PoNum, O.NumOfVials, O.PatCustId,
		IsNull((Select Top 1 ToteId From OrderToteAssoc with (NoLock) Where ((OrderId like O.OrderId + '-[0-9][0-9]') Or (OrderId = O.OrderId)) And OrderToteStateCode = 'I'),'') as ToteId
	Into #ReadyForPaperworkManPriority
	From OeOrder As O with (NoLock)
		Join
	OeOrderPoNumAssoc As Po with (NoLock)
		On O.OrderId = Po.OrderId
	Where
		((O.OrderStatus='Verified' And O.OrderId Not Like '%-[0-9][0-9]') Or
		 (O.OrderStatus = 'Split/MV' And O.StatusReason = 'Verified' And
		 (@MultiToteRequired = 0 Or (O.NumOfVials = (Select Count(OrderId) from OrderToteAssoc with (NoLock) Where OrderId like O.OrderId + '-[0-9][0-9]' And OrderToteStateCode = 'I')))))
	Order By
		O.DateFilled Asc

	-- Pulls the top 1 Manual to keep prioirty since manual travel time is far less than autofill
	Select Top(1) *
	From 
		#ReadyForPaperworkManPriority As RFP With (NoLock)
	Where
		@PatCustIdMask Like '%' + CAST((RFP.PatCustId % 10) as varchar) + '%' And
		FillType = 'M'

	UNION

	-- Pulls the next 10 items (Manual or Autofill)
	-- Since there is a 'UNION' and not a 'UNION ALL' duplicates are ignored
	Select Top(10) *
	From 
		#ReadyForPaperworkManPriority As RFP With (NoLock)
	Where
		@PatCustIdMask Like '%' + CAST((RFP.PatCustId % 10) as varchar) + '%'

	Order By
	   RFP.DateFilled Asc
