USE [PharmAssist]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PK_OeOrderHistory]    Script Date: 4/22/2026 2:53:08 PM ******/
ALTER TABLE [dbo].[OeOrderHistory] ADD  CONSTRAINT [PK_OeOrderHistory] PRIMARY KEY CLUSTERED 
(
	[OrderId] ASC,
	[HistoryDtTm] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 92, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [ByDateFilled]    Script Date: 4/22/2026 2:53:09 PM ******/
CREATE NONCLUSTERED INDEX [ByDateFilled] ON [dbo].[OeOrderHistory]
(
	[DateFilled] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [ByGroupNum]    Script Date: 4/22/2026 2:53:10 PM ******/
CREATE NONCLUSTERED INDEX [ByGroupNum] ON [dbo].[OeOrderHistory]
(
	[GroupNum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 92, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [ByHistoryDtTm]    Script Date: 4/22/2026 2:53:10 PM ******/
CREATE NONCLUSTERED INDEX [ByHistoryDtTm] ON [dbo].[OeOrderHistory]
(
	[HistoryDtTm] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 92, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [ByLastModifiedDtTm]    Script Date: 4/22/2026 2:53:11 PM ******/
CREATE NONCLUSTERED INDEX [ByLastModifiedDtTm] ON [dbo].[OeOrderHistory]
(
	[LastModifiedDtTm] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [ByOrderStatus]    Script Date: 4/22/2026 2:53:11 PM ******/
CREATE NONCLUSTERED INDEX [ByOrderStatus] ON [dbo].[OeOrderHistory]
(
	[OrderStatus] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 92, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [ByPatCustId]    Script Date: 4/22/2026 2:53:12 PM ******/
CREATE NONCLUSTERED INDEX [ByPatCustId] ON [dbo].[OeOrderHistory]
(
	[PatCustId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 92, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [ByRxNumRefillNum]    Script Date: 4/22/2026 2:53:13 PM ******/
CREATE NONCLUSTERED INDEX [ByRxNumRefillNum] ON [dbo].[OeOrderHistory]
(
	[RxNum] ASC,
	[RefillNum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 92, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


