USE [PharmAssist]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PK_OeOrderSecondaryData]    Script Date: 4/22/2026 10:53:18 AM ******/
ALTER TABLE [dbo].[OeOrderSecondaryData] ADD  CONSTRAINT [PK_OeOrderSecondaryData] PRIMARY KEY CLUSTERED 
(
	[OrderId] ASC,
	[HistoryDtTm] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [ByExtOrderNum]    Script Date: 4/22/2026 10:53:19 AM ******/
CREATE NONCLUSTERED INDEX [ByExtOrderNum] ON [dbo].[OeOrderSecondaryData]
(
	[ExtOrderNum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 92, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [ByHistoryDtTm]    Script Date: 4/22/2026 10:53:19 AM ******/
CREATE NONCLUSTERED INDEX [ByHistoryDtTm] ON [dbo].[OeOrderSecondaryData]
(
	[HistoryDtTm] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 92, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [ByLastModifiedDtTm]    Script Date: 4/22/2026 10:53:20 AM ******/
CREATE NONCLUSTERED INDEX [ByLastModifiedDtTm] ON [dbo].[OeOrderSecondaryData]
(
	[LastModifiedDtTm] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [ByPrevRxNum]    Script Date: 4/22/2026 10:53:21 AM ******/
CREATE NONCLUSTERED INDEX [ByPrevRxNum] ON [dbo].[OeOrderSecondaryData]
(
	[PrevRxNum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 92, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [BySourceRxId]    Script Date: 4/22/2026 10:53:21 AM ******/
CREATE NONCLUSTERED INDEX [BySourceRxId] ON [dbo].[OeOrderSecondaryData]
(
	[SourceRxId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 92, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


