-- Test batch generated from refactors/lsp_SrtGetSortationItems/Original.sql
-- Generated by tools/build_test_batch.py
-- DO NOT EDIT BY HAND; re-run the generator instead.

SET NOCOUNT OFF;  -- harness needs row counts visible

-- Parameter declarations
DECLARE @Barcode varchar(100) = NULL;
DECLARE @SortationCode varchar(30) = NULL;

-- Procedure body (verbatim from DDL, with EXEC lsp_DbLogSqlEvent commented out)
------------------------------------------------------------------------------------------------------------------------------------------------------
-- Procedure:
--      lsp_SrtGetSortationItems
--
-- Version:
--		2
--
-- Description:
--      Retrieves one or more Sortation Items based on the input parameters.
--      If no parameters are provided, retrieves all records from the table.
--
-- Parameters:
--      @Barcode            - Barcode for the Sortable Item (optional)
--      @SortationCode      - Sortation Code (optional)
--
------------------------------------------------------------------------------------------------------------------------------------------------------
BEGIN
    SET NOCOUNT ON;
    
    SELECT 
        Barcode,
        SortationCode
    FROM
        SrtSortationItem WITH (NOLOCK)
    WHERE 
        (@Barcode IS NULL OR Barcode = @Barcode) AND
        (@SortationCode IS NULL OR SortationCode = @SortationCode)
